steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fastapi-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'run',
      '--rm',
      '--entrypoint=pytest',
      'gcr.io/$PROJECT_ID/fastapi-app'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'swe-test-alantoris'
      - '--image=gcr.io/$PROJECT_ID/fastapi-app'
      - '--region=southamerica-east1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=latam-cc:southamerica-east1:fastapi-db'
